### ISSUE TITLE
PHP error on @Shervin Enayati

### ISSUE THREAD

**Issue by grumo** [USfoundation/us-indexer#67]
This Url gives error:
http://us.foundation/7?from=18

Error:

A PHP Error was encountered
Severity: Notice

Message: Undefined offset: 0

Filename: models/Us_model.php

Line Number: 273

Backtrace:

File: /var/www/us/application/models/Us_model.php
Line: 273
Function: _error_handler

File: /var/www/us/application/models/Us_model.php
Line: 306
Function: fetch_node

File: /var/www/us/application/controllers/Us.php
Line: 66
Function: fetch_node

File: /var/www/us/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Undefined index:

Filename: models/Us_model.php

Line Number: 307

Backtrace:

File: /var/www/us/application/models/Us_model.php
Line: 307
Function: _error_handler

File: /var/www/us/application/controllers/Us.php
Line: 66
Function: fetch_node

File: /var/www/us/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Undefined index:

Filename: models/Us_model.php

Line Number: 310

Backtrace:

File: /var/www/us/application/models/Us_model.php
Line: 310
Function: _error_handler

File: /var/www/us/application/controllers/Us.php
Line: 66
Function: fetch_node

File: /var/www/us/index.php
Line: 315
Function: require_once

**Comment by shervine** [comment]
@grumo Awesome feedback. Will have this bug fixed by tomorrow.

Keep making cards for the bugs you see or improvement ideas you have.

**Comment by shervine** [comment]
This is resolved, as this is the deeper issue: https://github.com/USfoundation/us-indexer/issues/71
